import { FlowBlock, Resource } from '@/types/resources';

export const RESOURCES: Resource[] = [
  {
    id: 'rapid-calculator',
    label: 'Calculadora Rápida',
    description: 'Precificação simples e direta para o dia a dia.',
    icon: 'Gauge',
  },
  {
    id: 'advanced-calculator',
    label: 'Calculadora Avançada',
    description: 'Cenários complexos com múltiplos fatores.',
    icon: 'Calculator',
  },
  {
    id: 'tax-calculator',
    label: 'Calculadora Tributária',
    description: 'Simulação precisa de impostos e taxas.',
    icon: 'Scale',
  },
  {
    id: 'bidding-calculator',
    label: 'Calculadora de Licitações',
    description: 'Precificação para propostas B2B e governo.',
    icon: 'Gavel',
  },
  {
    id: 'analytics',
    label: 'Dashboards e Analytics',
    description: 'Visão clara de métricas e desempenho.',
    icon: 'BarChart3',
  },
  {
    id: 'marketplaces',
    label: 'Marketplaces',
    description: 'Gestão e comparação de canais de venda.',
    icon: 'ShoppingBag',
  },
  {
    id: 'automation',
    label: 'Automações',
    description: 'Fluxos inteligentes e regras automáticas.',
    icon: 'Workflow',
  },
  {
    id: 'ai',
    label: 'Azuria IA',
    description: 'Assistente estratégico com inteligência artificial.',
    icon: 'BrainCircuit',
  },
];

export const FLOW_CONFIGS: Record<string, FlowBlock[]> = {
  'rapid-calculator': [
    {
      id: 'custo-produto',
      label: 'Custo do Produto',
      description: 'O ponto de partida do cálculo.',
      tooltip: 'O valor pago pelo produto, fornecedor ou fabricação. Se o custo estiver errado, todo o preço estará.',
      icon: 'Package',
      position: { x: 0, y: 0 },
    },
    {
      id: 'custos-operacionais',
      label: 'Custos Operacionais',
      description: 'Custos necessários para vender.',
      tooltip: 'Inclui embalagem, operação, logística e outros custos fixos ou variáveis.',
      icon: 'Settings',
      position: { x: 300, y: 0 },
    },
    {
      id: 'impostos',
      label: 'Impostos',
      description: 'Realidade fiscal aplicada.',
      tooltip: 'A Azuria considera impostos como ICMS e outras taxas conforme o contexto da venda.',
      icon: 'Scale',
      position: { x: 600, y: 0 },
      highlight: true,
    },
    {
      id: 'margem-desejada',
      label: 'Margem Desejada',
      description: 'Lucro definido conscientemente.',
      tooltip: 'Margem não é o que sobra. É o que você decide antes de vender.',
      icon: 'TrendingUp',
      position: { x: 900, y: 0 },
    },
    {
      id: 'preco-final',
      label: 'Preço Final',
      description: 'Resultado da decisão.',
      tooltip: 'Preço sugerido com base em todos os fatores anteriores, mostrando clareza e previsibilidade.',
      icon: 'CheckCircle',
      position: { x: 1200, y: 0 },
      highlight: true,
      size: 'large',
    },
  ],
  'advanced-calculator': [
    {
      id: 'inputs-avancados',
      label: 'Inputs Avançados',
      description: 'Múltiplos custos e variáveis.',
      tooltip: 'Configure custos variáveis, descontos progressivos e diferentes cenários de venda.',
      icon: 'Layers',
      position: { x: 0, y: 0 },
    },
    {
      id: 'impostos-multiplos',
      label: 'Impostos Múltiplos',
      description: 'ICMS, PIS, COFINS e outros.',
      tooltip: 'Simule a carga tributária completa considerando todos os impostos aplicáveis.',
      icon: 'Scale',
      position: { x: 300, y: 0 },
    },
    {
      id: 'taxas-adicionais',
      label: 'Taxas Adicionais',
      description: 'Marketplace, gateway e outras.',
      tooltip: 'Inclua taxas de plataformas, gateways de pagamento e serviços terceirizados.',
      icon: 'CreditCard',
      position: { x: 600, y: 0 },
    },
    {
      id: 'simulacao-cenarios',
      label: 'Simulação de Cenários',
      description: 'Compare diferentes estratégias.',
      tooltip: 'Veja lado a lado como diferentes configurações impactam margem e lucro final.',
      icon: 'GitCompare',
      position: { x: 900, y: 0 },
      highlight: true,
    },
    {
      id: 'resultado-detalhado',
      label: 'Resultado Detalhado',
      description: 'Análise completa e acionável.',
      tooltip: 'Receba uma análise detalhada com breakdown completo de custos, impostos e margem.',
      icon: 'FileText',
      position: { x: 1200, y: 0 },
      highlight: true,
      size: 'large',
    },
  ],
  'tax-calculator': [
    {
      id: 'tipo-produto',
      label: 'Tipo de Produto',
      description: 'Classificação do item.',
      tooltip: 'Defina o tipo de produto para aplicar as regras tributárias corretas.',
      icon: 'Package',
      position: { x: 0, y: 0 },
    },
    {
      id: 'regime-tributario',
      label: 'Regime Tributário',
      description: 'Simples, Lucro Presumido ou Real.',
      tooltip: 'Selecione o regime tributário da sua empresa para cálculos precisos.',
      icon: 'Building2',
      position: { x: 300, y: 0 },
      highlight: true,
    },
    {
      id: 'origem-destino',
      label: 'Origem e Destino',
      description: 'Estados envolvidos na operação.',
      tooltip: 'Informe origem e destino para calcular ICMS interestadual corretamente.',
      icon: 'MapPin',
      position: { x: 600, y: 0 },
    },
    {
      id: 'calculo-impostos',
      label: 'Cálculo de Impostos',
      description: 'ICMS, PIS, COFINS e outros.',
      tooltip: 'A Azuria calcula automaticamente todos os impostos aplicáveis ao seu cenário.',
      icon: 'Calculator',
      position: { x: 900, y: 0 },
    },
    {
      id: 'impacto-tributario',
      label: 'Impacto Tributário',
      description: 'Visão clara da carga fiscal.',
      tooltip: 'Veja exatamente quanto de impostos impacta seu preço final e margem de lucro.',
      icon: 'TrendingDown',
      position: { x: 1200, y: 0 },
      highlight: true,
      size: 'large',
    },
  ],
  'bidding-calculator': [
    {
      id: 'requisitos-licitacao',
      label: 'Requisitos da Licitação',
      description: 'Entenda o edital completo.',
      tooltip: 'Analise todos os requisitos, condições e especificações do edital.',
      icon: 'FileText',
      position: { x: 0, y: 0 },
    },
    {
      id: 'custos-completos',
      label: 'Custos Completos',
      description: 'Todos os custos envolvidos.',
      tooltip: 'Inclua custos de produção, logística, impostos específicos e margem de segurança.',
      icon: 'DollarSign',
      position: { x: 300, y: 0 },
    },
    {
      id: 'impostos-licitacao',
      label: 'Impostos Específicos',
      description: 'Tributos aplicáveis a licitações.',
      tooltip: 'Considere impostos específicos como ISS, ICMS e retenções na fonte.',
      icon: 'Scale',
      position: { x: 600, y: 0 },
      highlight: true,
    },
    {
      id: 'margem-seguranca',
      label: 'Margem de Segurança',
      description: 'Proteção contra imprevistos.',
      tooltip: 'Adicione uma margem de segurança para cobrir variações e garantir rentabilidade.',
      icon: 'Shield',
      position: { x: 900, y: 0 },
    },
    {
      id: 'lance-minimo',
      label: 'Lance Mínimo',
      description: 'Preço seguro para vencer.',
      tooltip: 'Receba o lance mínimo recomendado que mantém sua margem e competitividade.',
      icon: 'Gavel',
      position: { x: 1200, y: 0 },
      highlight: true,
      size: 'large',
    },
  ],
  'analytics': [
    {
      id: 'coleta-dados',
      label: 'Coleta de Dados',
      description: 'Histórico de cálculos e vendas.',
      tooltip: 'A Azuria coleta automaticamente dados de todos os seus cálculos e vendas.',
      icon: 'Database',
      position: { x: 0, y: 0 },
    },
    {
      id: 'processamento',
      label: 'Processamento',
      description: 'Análise e agregação inteligente.',
      tooltip: 'Os dados são processados e organizados para gerar insights acionáveis.',
      icon: 'Cpu',
      position: { x: 300, y: 0 },
    },
    {
      id: 'metricas-chave',
      label: 'Métricas-Chave',
      description: 'Margem, volume e tendências.',
      tooltip: 'Acompanhe métricas essenciais como margem média, volume de vendas e tendências.',
      icon: 'BarChart3',
      position: { x: 600, y: 0 },
      highlight: true,
    },
    {
      id: 'visualizacoes',
      label: 'Visualizações',
      description: 'Gráficos e dashboards interativos.',
      tooltip: 'Visualize seus dados em gráficos claros e dashboards interativos.',
      icon: 'LineChart',
      position: { x: 900, y: 0 },
    },
    {
      id: 'insights',
      label: 'Insights',
      description: 'Recomendações acionáveis.',
      tooltip: 'Receba insights e recomendações baseados em seus dados históricos.',
      icon: 'Lightbulb',
      position: { x: 1200, y: 0 },
      highlight: true,
      size: 'large',
    },
  ],
  'marketplaces': [
    {
      id: 'conexao-marketplaces',
      label: 'Conexão com Marketplaces',
      description: 'Integre seus canais de venda.',
      tooltip: 'Conecte seus marketplaces favoritos para sincronização automática de dados.',
      icon: 'Plug',
      position: { x: 0, y: 0 },
    },
    {
      id: 'coleta-taxas',
      label: 'Coleta de Taxas',
      description: 'Taxas reais de cada plataforma.',
      tooltip: 'A Azuria coleta automaticamente as taxas atualizadas de cada marketplace.',
      icon: 'Receipt',
      position: { x: 300, y: 0 },
    },
    {
      id: 'comparacao',
      label: 'Comparação',
      description: 'Compare margens entre canais.',
      tooltip: 'Veja lado a lado qual marketplace oferece melhor margem para seus produtos.',
      icon: 'GitCompare',
      position: { x: 600, y: 0 },
      highlight: true,
    },
    {
      id: 'estrategia-preco',
      label: 'Estratégia de Preço',
      description: 'Preços otimizados por canal.',
      tooltip: 'Receba recomendações de preços específicas para cada marketplace.',
      icon: 'Target',
      position: { x: 900, y: 0 },
    },
    {
      id: 'dashboard-unificado',
      label: 'Dashboard Unificado',
      description: 'Visão consolidada de performance.',
      tooltip: 'Acompanhe a performance de todos os seus canais em um único lugar.',
      icon: 'LayoutDashboard',
      position: { x: 1200, y: 0 },
      highlight: true,
      size: 'large',
    },
  ],
  'automation': [
    {
      id: 'gatilhos',
      label: 'Gatilhos',
      description: 'Defina quando acionar a automação.',
      tooltip: 'Configure gatilhos baseados em preço, estoque, margem ou outros critérios.',
      icon: 'Zap',
      position: { x: 0, y: 0 },
    },
    {
      id: 'condicoes',
      label: 'Condições',
      description: 'Regras e lógica de negócio.',
      tooltip: 'Defina condições complexas que determinam quando a automação deve executar.',
      icon: 'Code',
      position: { x: 300, y: 0 },
    },
    {
      id: 'acoes',
      label: 'Ações',
      description: 'O que acontece quando acionado.',
      tooltip: 'Configure ações automáticas como ajuste de preço, notificações ou integrações.',
      icon: 'Play',
      position: { x: 600, y: 0 },
      highlight: true,
    },
    {
      id: 'execucao',
      label: 'Execução',
      description: 'Processamento automático.',
      tooltip: 'A automação executa suas ações de forma confiável e em tempo real.',
      icon: 'Cog',
      position: { x: 900, y: 0 },
    },
    {
      id: 'monitoramento',
      label: 'Monitoramento',
      description: 'Acompanhe o desempenho.',
      tooltip: 'Monitore todas as execuções e receba alertas sobre o desempenho das automações.',
      icon: 'Activity',
      position: { x: 1200, y: 0 },
      highlight: true,
      size: 'large',
    },
  ],
  'ai': [
    {
      id: 'entrada-contexto',
      label: 'Entrada de Contexto',
      description: 'Forneça informações sobre seu negócio.',
      tooltip: 'A IA precisa entender seu contexto: produtos, mercado, objetivos e desafios.',
      icon: 'MessageSquare',
      position: { x: 0, y: 0 },
    },
    {
      id: 'processamento-ia',
      label: 'Processamento IA',
      description: 'Análise inteligente dos dados.',
      tooltip: 'A inteligência artificial analisa padrões, tendências e oportunidades.',
      icon: 'BrainCircuit',
      position: { x: 300, y: 0 },
      highlight: true,
    },
    {
      id: 'geracao-insights',
      label: 'Geração de Insights',
      description: 'Recomendações personalizadas.',
      tooltip: 'Receba insights e recomendações específicas para seu contexto de negócio.',
      icon: 'Sparkles',
      position: { x: 600, y: 0 },
    },
    {
      id: 'explicacao',
      label: 'Explicação',
      description: 'Entenda o raciocínio da IA.',
      tooltip: 'A IA explica de forma clara e humana por que cada recomendação foi feita.',
      icon: 'BookOpen',
      position: { x: 900, y: 0 },
    },
    {
      id: 'decisao-informada',
      label: 'Decisão Informada',
      description: 'Ação com confiança.',
      tooltip: 'Tome decisões de precificação com confiança, apoiado por inteligência artificial.',
      icon: 'CheckCircle',
      position: { x: 1200, y: 0 },
      highlight: true,
      size: 'large',
    },
  ],
};

