name: Azure Infrastructure Deployment

on:
    workflow_dispatch:
    push:
        branches: [main]
        paths:
            - "infra/**"
            - "azure.yaml"

permissions:
    contents: read
    id-token: write

jobs:
    deploy-infrastructure:
        runs-on: ubuntu-latest
        name: Deploy Azure Infrastructure

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Azure CLI
              uses: azure/setup-azd@v1.0.0

            - name: Log in to Azure using OIDC
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.AZURE_CLIENT_ID }}
                  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                  subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - name: Provision Infrastructure
              run: azd provision --preview
              env:
                  AZURE_ENV_NAME: ${{ secrets.AZURE_ENV_NAME }}
                  AZURE_LOCATION: ${{ secrets.AZURE_LOCATION }}
                  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - name: Deploy Infrastructure
              if: github.ref == 'refs/heads/main'
              run: azd provision --no-prompt
              env:
                  AZURE_ENV_NAME: ${{ secrets.AZURE_ENV_NAME }}
                  AZURE_LOCATION: ${{ secrets.AZURE_LOCATION }}
                  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
