name: Commitlint

on:
  pull_request:
    branches: [ main ]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - name: Lint commit messages
        run: |
          npx commitlint --from=$GITHUB_SHA~50 --to=$GITHUB_SHA || npx commitlint --last
