name: Coverage

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'coverage/coverage-badge.svg' # avoid infinite loops on badge-only commits
  pull_request:
    branches: [ main ]

jobs:
  vitest-coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # needed to commit updated badge on main
      actions: read
      checks: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Coverage gate
        run: npm run coverage:gate

      - name: Generate coverage badge
        run: node scripts/generate-coverage-badge.mjs

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage
          if-no-files-found: warn

      - name: Commit updated coverage badge (main only)
        if: github.ref == 'refs/heads/main'
        run: |
          if git diff --quiet coverage/coverage-badge.svg; then
            echo "No badge changes to commit"
          else
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add coverage/coverage-badge.svg
            git commit -m "chore(coverage): update coverage badge [skip ci]"
            git push
          fi
