name: Package Manager Guard

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify only npm is used
        run: node scripts/verify-package-manager.mjs
