name: Security Headers

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 3 * * *' # diário 03:00 UTC

jobs:
  check-security-headers:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm ci

      - name: Verificar cabeçalhos (produção)
        run: |
          PROD_URL="${{ secrets.PROD_APP_URL }}"
          if [ -n "$PROD_URL" ]; then
            echo "Usando PROD_APP_URL=$PROD_URL";
            SECURITY_CHECK_URL="$PROD_URL" node scripts/check-security-headers.mjs;
          else
            echo "PROD_APP_URL não definido - tentativa localhost (não falha se indisponível)";
            node scripts/check-security-headers.mjs http://localhost:4173 || echo "(Aviso) localhost indisponível";
          fi
